services:
  - type: web
    name: payments-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: payments-api-db
          property: connectionString
      - key: RAILS_ENV
        value: production

databases:
  - name: payments-api-db
    databaseName: payments_api
    user: payments_api
