default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['PG_HOST'] %>
  database: app_payment
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: app_payment_test
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  <<: *default
  database: payments_api_production
  username: payments_api
  password: <%= ENV["PAYMENTS_API_DATABASE_PASSWORD"] %>
